"""Shared fixtures for pytest."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

FIXTURE_DIR = Path(__file__).parent / "fixtures"
CORPUS_FIXTURE = FIXTURE_DIR / "corpus_paths.json"


@pytest.fixture(scope="session")
def corpus_paths() -> dict[str, list[str]]:
    """Load cached corpus paths from the fixture file.

    The fixture is generated by ``pylib/tools/gen_corpus_fixture.py`` and
    contains ``{"all": [...], "media": [...]}``.  If the fixture is
    missing, it is regenerated automatically when the NAS is mounted.
    """
    if not CORPUS_FIXTURE.exists():
        # Try to generate it on-the-fly if the NAS is mounted.
        import subprocess
        import sys

        result = subprocess.run(
            [
                sys.executable,
                str(Path(__file__).parent.parent / "tools" / "gen_corpus_fixture.py"),
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0 or not CORPUS_FIXTURE.exists():
            pytest.skip(
                "Corpus fixture not available (run gen_corpus_fixture.py with NAS mounted)"
            )

    data = json.loads(CORPUS_FIXTURE.read_text(encoding="utf-8"))
    if not data.get("all"):
        pytest.skip("Corpus fixture is empty")
    return data
